export interface Service {
  slug: string;
  title: string;
  tagline: string;
  seoTitle: string;
  seoDescription: string;
  icon: string;
  category: string;
  hourlyRate: number;
  retainerFrom: number;
  setupFrom: number;
  heroStatement: string;
  problem: string;
  solution: string;
  whatWeDeliver: string[];
  process: { step: string; title: string; body: string }[];
  whoItsFor: string[];
  results: { stat: string; label: string }[];
}

export const services: Service[] = [
  {
    slug: 'ai-lead-response-agent',
    title: 'AI Lead Response Agent',
    tagline: 'Never lose a lead to slow response time again.',
    seoTitle: 'AI Lead Response Agent | Voice of Cash',
    seoDescription: 'Respond to every inbound lead in under 90 seconds, 24/7. Our AI lead response agents qualify, score, and route hot prospects before your competitors call back.',
    icon: '⚡',
    category: 'Revenue',
    hourlyRate: 149,
    retainerFrom: 1200,
    setupFrom: 1800,
    heroStatement: 'The business that responds first wins. Right now, that is not you.',
    problem: 'The average business takes 47 hours to respond to a new inquiry. Studies show that the odds of qualifying a lead drop by 80 percent after just five minutes. Every hour your inquiry sits unanswered is a lead your competitor is closing.',
    solution: 'We build and deploy an AI lead response agent that responds to every inbound inquiry within 90 seconds — day, night, weekends, holidays. It asks the right qualification questions, scores the prospect against your ideal customer profile, and routes hot leads to your team with full context. Cold leads get nurtured. Hot leads get humans.',
    whatWeDeliver: [
      'Custom-trained AI agent that responds to web forms, texts, and emails instantly',
      'Lead qualification flow built around your specific service and client profile',
      'Automated lead scoring with hot/warm/cold routing logic',
      'CRM integration — every qualified lead lands in your pipeline automatically',
      'Weekly performance report: leads captured, qualified, converted',
      'Human escalation triggers for high-value prospects',
    ],
    process: [
      { step: '01', title: 'Discovery', body: 'We map your current lead flow, identify where leads are dropping off, and define your ideal customer profile and qualification criteria.' },
      { step: '02', title: 'Build', body: 'We build the agent, write the qualification sequences, and integrate with your existing CRM and communication stack.' },
      { step: '03', title: 'Test', body: 'We run the agent in parallel with your existing process for 2 weeks, comparing performance and tuning responses.' },
      { step: '04', title: 'Deploy', body: 'The agent goes live. Your team gets a dashboard showing every lead interaction and a real-time escalation feed for hot prospects.' },
    ],
    whoItsFor: ['Service businesses with high inbound volume', 'Real estate agents and brokerages', 'Medical and dental practices', 'Law firms handling consumer inquiries', 'Home services contractors', 'Any business that loses leads to slow follow-up'],
    results: [
      { stat: '90s', label: 'average response time' },
      { stat: '3×', label: 'more leads qualified' },
      { stat: '47hrs', label: 'avg competitor response time' },
      { stat: '80%', label: 'conversion drop after 5 min' },
    ],
  },
  {
    slug: 'ai-customer-service-agent',
    title: 'AI Customer Service Agent',
    tagline: 'World-class support without the world-class payroll.',
    seoTitle: 'AI Customer Service Agent Las Vegas | Voice of Cash',
    seoDescription: 'Handle FAQs, complaints, and follow-ups automatically 24/7. Our AI customer service agents resolve 70-80% of inquiries without human involvement.',
    icon: '🎧',
    category: 'Operations',
    hourlyRate: 149,
    retainerFrom: 1400,
    setupFrom: 2200,
    heroStatement: 'Your customers expect an answer now. Your team cannot be everywhere. We fix that.',
    problem: 'Customer service is one of the highest-cost, highest-turnover functions in any business. Staff answering the same 15 questions on repeat. Response times stretching hours. Customer satisfaction scores that reflect the inconsistency of human memory and mood. There is a better way.',
    solution: 'We build an AI customer service agent trained specifically on your business — your products, your policies, your tone, your edge cases. It handles the repetitive 70 to 80 percent of interactions automatically, escalates the complex cases to your team with full context, and maintains consistent, professional quality at any volume, at any hour.',
    whatWeDeliver: [
      'Custom AI agent trained on your FAQs, policies, and product/service catalog',
      'Multi-channel deployment: website chat, email, SMS',
      'Sentiment detection with priority escalation for frustrated customers',
      'Escalation handoff system with full conversation context for your team',
      'Monthly performance dashboard: resolution rate, escalation rate, CSAT scores',
      'Quarterly retraining sessions to improve accuracy and handle new scenarios',
    ],
    process: [
      { step: '01', title: 'Knowledge Audit', body: 'We catalog every FAQ, policy, and common scenario your support team handles. This becomes the foundation of your agent\'s training.' },
      { step: '02', title: 'Agent Build', body: 'We build and train the agent, configure escalation triggers, and integrate with your customer communication channels.' },
      { step: '03', title: 'Shadow Period', body: 'The agent runs alongside your team for 2 weeks. We compare its responses to your team\'s and tune accuracy before full deployment.' },
      { step: '04', title: 'Live + Optimize', body: 'Agent goes fully live. We monitor performance weekly in the first 90 days and optimize based on real interaction data.' },
    ],
    whoItsFor: ['E-commerce businesses with high support volume', 'Subscription businesses with recurring inquiries', 'Service businesses managing client communications', 'Hospitality and restaurant groups', 'Healthcare practices with appointment and billing questions'],
    results: [
      { stat: '78%', label: 'avg resolution without human' },
      { stat: '38s', label: 'avg response time' },
      { stat: '24/7', label: 'coverage with zero overtime' },
      { stat: '40%', label: 'typical support cost reduction' },
    ],
  },
  {
    slug: 'ai-appointment-booking-agent',
    title: 'AI Appointment Booking Agent',
    tagline: 'Fill your calendar automatically. Sleep while it works.',
    seoTitle: 'AI Appointment Booking Agent | Voice of Cash',
    seoDescription: 'End-to-end scheduling automation for service businesses. Our AI booking agents schedule, confirm, remind, and reschedule without your front desk touching it.',
    icon: '📅',
    category: 'Operations',
    hourlyRate: 149,
    retainerFrom: 900,
    setupFrom: 1500,
    heroStatement: 'Every missed call is a missed booking. Every double-booking is a client you lose.',
    problem: 'Scheduling is one of the most time-consuming, error-prone tasks in a service business. Phone tags. Double bookings. No-shows because reminders were not sent. Front desk staff spending 30 percent of their time on calendar management instead of serving the clients who are actually there.',
    solution: 'We build an AI booking agent that handles every step of the scheduling process end-to-end. It takes the booking, finds the right availability, confirms the appointment, sends reminders at the right intervals, handles reschedule requests, and fills canceled slots from a waitlist — automatically, without human intervention.',
    whatWeDeliver: [
      'AI booking agent deployable via web, SMS, and phone',
      'Real-time calendar integration with your existing system',
      'Automated confirmation, reminder, and reschedule sequences',
      'No-show reduction workflow with pre-appointment check-ins',
      'Waitlist management to automatically fill canceled slots',
      'Post-appointment follow-up and review request triggers',
    ],
    process: [
      { step: '01', title: 'Calendar Audit', body: 'We map your current booking flow, identify drop-off points, and define the scheduling rules your agent needs to follow.' },
      { step: '02', title: 'Integration Build', body: 'We integrate with your calendar system, build the booking agent, and configure the full confirmation and reminder sequence.' },
      { step: '03', title: 'Test Runs', body: 'We run live test bookings across every channel — web, SMS, phone — before flipping the switch.' },
      { step: '04', title: 'Deploy', body: 'Agent goes live. Your front desk team shifts from managing the calendar to focusing on in-person client experience.' },
    ],
    whoItsFor: ['Medical and dental practices', 'Salons, spas, and wellness studios', 'Legal and financial services firms', 'Personal trainers and coaches', 'Home services contractors', 'Any service business that books appointments'],
    results: [
      { stat: '100%', label: 'inquiries responded to' },
      { stat: '30%', label: 'reduction in no-show rate' },
      { stat: '0', label: 'double-bookings' },
      { stat: '3hrs', label: 'avg front desk time saved daily' },
    ],
  },
  {
    slug: 'ai-sales-funnel-build',
    title: 'AI Sales Funnel Build',
    tagline: 'From first click to closed deal — automated.',
    seoTitle: 'AI Sales Funnel Build Las Vegas | Voice of Cash',
    seoDescription: 'Full sales funnel automation from landing page to closed deal. Lead capture, nurture sequences, scoring, and handoff — all built and running for your business.',
    icon: '🎯',
    category: 'Revenue',
    hourlyRate: 149,
    retainerFrom: 2200,
    setupFrom: 3500,
    heroStatement: 'Your leads are leaking. An AI-powered funnel seals every gap.',
    problem: 'Most businesses have a collection of disconnected pieces that are supposed to function as a sales funnel. A landing page here. An email list there. A CRM that nobody updates. The result is leads that enter at the top and disappear without explanation before they ever become clients.',
    solution: 'We design and build a complete AI-powered sales funnel — from the first ad click to the signed contract. Every stage is connected. Every lead is tracked. Nurture sequences are personalized based on behavior. Scoring triggers the right follow-up at the right moment. And when a prospect is ready to buy, your sales team has everything they need to close.',
    whatWeDeliver: [
      'Full funnel architecture design mapped to your specific sales process',
      'Landing page or lead capture integration',
      'Automated lead nurture sequence (email + SMS, 7-14 touchpoints)',
      'Behavioral scoring that triggers different paths based on engagement',
      'Proposal or quote automation for qualified prospects',
      'CRM integration with pipeline stage automation',
      'Closed-loop reporting from first touch to closed deal',
    ],
    process: [
      { step: '01', title: 'Funnel Mapping', body: 'We map your buyer journey from awareness to decision, identifying every stage, every touchpoint, and every current gap.' },
      { step: '02', title: 'Content & Copy', body: 'We write the nurture sequences, create the scoring logic, and design the automation triggers for every stage.' },
      { step: '03', title: 'Build & Connect', body: 'We build the technical infrastructure, connect all the pieces, and integrate with your CRM and communication stack.' },
      { step: '04', title: 'Launch & Tune', body: 'Funnel goes live. We monitor performance weekly for the first 90 days and optimize based on conversion data.' },
    ],
    whoItsFor: ['B2B service businesses with longer sales cycles', 'Coaches and consultants', 'High-ticket service providers', 'Businesses with existing traffic that is not converting', 'Companies moving from manual sales to scalable process'],
    results: [
      { stat: '18%', label: 'avg pipeline conversion increase' },
      { stat: '7-14', label: 'automated touchpoints per lead' },
      { stat: '60%', label: 'reduction in manual sales tasks' },
      { stat: '3×', label: 'more leads reached per rep hour' },
    ],
  },
  {
    slug: 'ai-reputation-management',
    title: 'AI Reputation & Review Management',
    tagline: 'Own your reputation before someone else does.',
    seoTitle: 'AI Reputation Management Las Vegas | Voice of Cash',
    seoDescription: 'Monitor every review platform, respond automatically, flag negative reviews early, and trigger review requests from happy customers. All automated.',
    icon: '⭐',
    category: 'Brand',
    hourlyRate: 149,
    retainerFrom: 800,
    setupFrom: 1200,
    heroStatement: '93% of customers read reviews before buying. What yours say right now is a sales call happening without you.',
    problem: 'Most businesses respond to reviews inconsistently — or not at all. Negative reviews sit unanswered. Happy customers are never asked to share their experience. The result is a review profile that reflects the loudest voices, not the typical experience — and a silent sales problem you cannot see.',
    solution: 'We deploy an AI reputation management system that monitors every platform where your business is reviewed, drafts responses to every review for approval or auto-sends based on your rules, flags negative reviews for immediate human attention, and automatically requests reviews from satisfied customers at the right moment in the post-service experience.',
    whatWeDeliver: [
      'Multi-platform monitoring: Google, Yelp, Facebook, industry-specific platforms',
      'AI-drafted responses to every review, matched to your brand voice',
      'Negative review alert system with escalation to designated team member',
      'Automated review request sequences triggered by post-service workflows',
      'Monthly reputation report: volume, sentiment, trend, response rate',
      'Competitive reputation benchmarking against your top local competitors',
    ],
    process: [
      { step: '01', title: 'Platform Audit', body: 'We audit your current review profile across all platforms, identify gaps, and define your response voice and escalation rules.' },
      { step: '02', title: 'System Build', body: 'We connect monitoring across all relevant platforms and build the response and alert infrastructure.' },
      { step: '03', title: 'Review Request Flow', body: 'We build the post-service review request sequence integrated with your customer communication process.' },
      { step: '04', title: 'Ongoing Management', body: 'System runs continuously. Monthly reports delivered. Quarterly check-ins to optimize strategy.' },
    ],
    whoItsFor: ['Restaurants and hospitality businesses', 'Medical and dental practices', 'Home services contractors', 'Retail businesses with local presence', 'Any business where reviews directly influence customer decisions'],
    results: [
      { stat: '93%', label: 'of buyers read reviews first' },
      { stat: '2×', label: 'more reviews from automated requests' },
      { stat: '100%', label: 'response rate on all reviews' },
      { stat: '4hr', label: 'avg time to flag negative reviews' },
    ],
  },
  {
    slug: 'ai-email-sms-automation',
    title: 'AI Email & SMS Automation',
    tagline: 'Your message. The right person. The right moment. Automatically.',
    seoTitle: 'AI Email & SMS Automation Las Vegas | Voice of Cash',
    seoDescription: 'Nurture sequences, reactivation campaigns, event triggers, and segmentation — all built and running without manual sends. AI-powered email and SMS automation.',
    icon: '📨',
    category: 'Revenue',
    hourlyRate: 149,
    retainerFrom: 1100,
    setupFrom: 1800,
    heroStatement: 'Your email list is the most valuable asset in your business. Most companies barely use it.',
    problem: 'An email list that is not being actively worked is money sitting idle. Most businesses send a newsletter when they remember to, batch-blast their entire list with the same message, and watch open rates slowly decline. The relationship with the customer deteriorates. Reactivation becomes increasingly difficult.',
    solution: 'We build AI-powered email and SMS automation that treats every contact as an individual — segmenting based on behavior, sending messages triggered by real actions, and personalizing content based on where each contact is in their journey with your business. The result is communication that feels relevant and timely rather than mass and random.',
    whatWeDeliver: [
      'Welcome sequence for new subscribers and new clients',
      'Behavior-triggered email flows based on website activity and purchase history',
      'Win-back campaign for dormant contacts',
      'Transactional SMS sequences for appointments, orders, and time-sensitive communication',
      'List segmentation architecture and ongoing management',
      'A/B testing framework for subject lines, content, and send times',
      'Monthly performance reporting: open rates, click rates, conversion rates, revenue attributed',
    ],
    process: [
      { step: '01', title: 'List Audit', body: 'We analyze your current list health, segmentation, and historical performance to identify the highest-value automation opportunities.' },
      { step: '02', title: 'Strategy & Copy', body: 'We map all automation flows, write the sequences, and define the behavioral triggers for each campaign.' },
      { step: '03', title: 'Build & Test', body: 'We build every flow in your email platform, test all triggers and segments, and validate the full send experience before launch.' },
      { step: '04', title: 'Launch & Optimize', body: 'Automations go live. We monitor performance weekly for the first 60 days and optimize based on engagement data.' },
    ],
    whoItsFor: ['E-commerce businesses with existing customer lists', 'Service businesses with repeat purchase potential', 'Subscription companies managing retention', 'Coaches and consultants with lead nurture needs', 'Any business with an underutilized email list'],
    results: [
      { stat: '35%', label: 'avg open rate for triggered emails' },
      { stat: '5×', label: 'more revenue per list member' },
      { stat: '28%', label: 'win-back rate on dormant contacts' },
      { stat: '0hrs', label: 'manual send time after setup' },
    ],
  },
  {
    slug: 'ai-social-media-content-agent',
    title: 'AI Social Media & Content Agent',
    tagline: 'Stay active everywhere without running yourself ragged.',
    seoTitle: 'AI Social Media Content Agent Las Vegas | Voice of Cash',
    seoDescription: 'AI-generated, scheduled, and posted content across every platform your business needs to be on. Keep your brand active without manual effort every day.',
    icon: '📱',
    category: 'Brand',
    hourlyRate: 149,
    retainerFrom: 1000,
    setupFrom: 1400,
    heroStatement: 'Your competitors are posting every day. You are not. That gap is costing you visibility.',
    problem: 'Consistent social media presence is one of the most important things a local business can maintain — and one of the hardest to sustain manually. Creating content takes time. Scheduling takes discipline. Knowing what to say and when requires strategy. Most businesses do it sporadically and wonder why it is not working.',
    solution: 'We build an AI content pipeline that generates brand-consistent social media content, schedules it across your active platforms, and monitors performance to continuously improve what gets created. You review and approve — or set it to fully automated. Either way, your brand stays active and consistent without consuming your time.',
    whatWeDeliver: [
      'Content strategy and brand voice documentation',
      'AI-generated post calendar — 3 to 5 posts per week per platform',
      'Platform-specific formatting for Instagram, Facebook, LinkedIn, X, Google Business',
      'Image prompt briefs and caption copy for every post',
      'Scheduling integration with your social media management tool',
      'Monthly content performance report with engagement benchmarks',
      'Quarterly content strategy review and refresh',
    ],
    process: [
      { step: '01', title: 'Brand Voice Build', body: 'We document your brand voice, content pillars, audience profile, and the topics your business owns. This trains your content agent.' },
      { step: '02', title: 'Content System Build', body: 'We build the generation pipeline, connect your scheduling platform, and create the first month of content for review.' },
      { step: '03', title: 'Review & Approve', body: 'You review the first batch. We refine based on your feedback until the output matches your standards.' },
      { step: '04', title: 'Run & Report', body: 'System runs monthly. You get a performance report and a content preview for the upcoming month for any final adjustments.' },
    ],
    whoItsFor: ['Local businesses that know they need social presence but cannot sustain it', 'Service businesses with expertise worth sharing', 'Restaurants, retailers, and hospitality businesses', 'Coaches and consultants building personal brand', 'Any business spending too much time thinking about what to post'],
    results: [
      { stat: '5×', label: 'posting frequency vs. manual' },
      { stat: '100%', label: 'brand consistency across platforms' },
      { stat: '8hrs', label: 'avg weekly content time saved' },
      { stat: '3mo', label: 'typical organic reach improvement' },
    ],
  },
  {
    slug: 'ai-crm-build-automation',
    title: 'AI CRM Build & Automation',
    tagline: 'A CRM that actually works — because it runs itself.',
    seoTitle: 'AI CRM Build & Automation Las Vegas | Voice of Cash',
    seoDescription: 'We build your CRM, automate data entry, keep contacts clean, and trigger actions based on pipeline stage. No more manual updates. No more data you cannot trust.',
    icon: '🗄️',
    category: 'Operations',
    hourlyRate: 149,
    retainerFrom: 1300,
    setupFrom: 2500,
    heroStatement: 'A CRM nobody updates is not a tool. It is a liability.',
    problem: 'Most businesses have a CRM. Very few use it effectively. Data entry is manual and inconsistent. Records go stale. Pipeline stages are not updated. The result is a database you cannot trust — which means the reports it generates are meaningless and the automated workflows that depend on it do not trigger.',
    solution: 'We build or rebuild your CRM with an AI automation layer that handles data entry automatically, keeps records clean, triggers actions based on pipeline movement, and generates reliable reporting. Your team stops updating spreadsheets and starts using a system that tells them exactly what to do next.',
    whatWeDeliver: [
      'CRM audit or fresh build in your platform of choice',
      'Automated data capture from all lead sources into clean CRM records',
      'Pipeline stage automation with trigger-based task creation',
      'Contact enrichment and deduplication workflows',
      'Automated follow-up task generation based on deal inactivity',
      'Sales team activity logging without manual input',
      'Weekly pipeline report delivered automatically to leadership',
    ],
    process: [
      { step: '01', title: 'Audit', body: 'We audit your current CRM state, data quality, and the workflows that should be running but are not. We map the gap.' },
      { step: '02', title: 'Architecture', body: 'We design the pipeline structure, automation rules, and integration map for your specific business and sales process.' },
      { step: '03', title: 'Build & Migrate', body: 'We build or rebuild the CRM, migrate clean data, and connect all lead sources and communication tools.' },
      { step: '04', title: 'Train & Optimize', body: 'Team training on the new system. 30-day monitoring period with weekly optimization based on actual usage patterns.' },
    ],
    whoItsFor: ['Sales teams managing complex pipelines', 'Service businesses tracking client lifecycle', 'Companies with multiple lead sources that need centralization', 'Businesses whose CRM data they no longer trust', 'Teams spending significant time on manual data entry'],
    results: [
      { stat: '90%', label: 'reduction in manual data entry' },
      { stat: '100%', label: 'pipeline visibility for leadership' },
      { stat: '2×', label: 'faster deal progression' },
      { stat: '0', label: 'stale records after 90 days' },
    ],
  },
  {
    slug: 'ai-phone-receptionist',
    title: 'AI Phone Receptionist',
    tagline: 'Every call answered. Every lead captured. Zero missed opportunities.',
    seoTitle: 'AI Phone Receptionist Las Vegas | Voice of Cash',
    seoDescription: 'An AI voice receptionist that answers calls, captures information, books appointments, and routes urgent matters. Never miss a call or a lead again.',
    icon: '📞',
    category: 'Operations',
    hourlyRate: 149,
    retainerFrom: 950,
    setupFrom: 1600,
    heroStatement: 'The call that goes to voicemail is the customer calling your competitor next.',
    problem: 'Phone calls are still the highest-intent inquiry channel in local business. A person who calls wants to buy now. And yet most local businesses miss calls during lunch, after hours, when the front desk is with another customer, or when the phone just rings too many times. Every missed call is a lost opportunity.',
    solution: 'We deploy an AI phone receptionist that answers every call professionally, captures the caller\'s information and reason for calling, books appointments directly into your calendar, handles common FAQs with your actual answers, and routes urgent matters to the right person immediately. It sounds professional, responds naturally, and never takes a sick day.',
    whatWeDeliver: [
      'Custom AI voice agent trained on your business, services, and scripts',
      'Live calendar integration for real-time appointment booking',
      'Call routing logic for different inquiry types',
      'Full call transcripts delivered to your team after every call',
      'Urgent call escalation to designated mobile number',
      'After-hours message capture with next-day follow-up triggers',
      'Monthly call analytics: volume, inquiry types, booking conversion rate',
    ],
    process: [
      { step: '01', title: 'Script Development', body: 'We write the complete call script — greetings, FAQ responses, booking flows, and escalation triggers — based on your actual business.' },
      { step: '02', title: 'Voice Build', body: 'We build and configure the AI voice agent, integrate with your phone system and calendar, and test every call scenario.' },
      { step: '03', title: 'Live Testing', body: 'We run test calls across every scenario. Your team reviews transcripts and provides feedback before full deployment.' },
      { step: '04', title: 'Deploy', body: 'Receptionist goes live on your business line. You get a weekly call summary and can request script updates at any time.' },
    ],
    whoItsFor: ['Medical, dental, and legal offices', 'Home services contractors', 'Salons, spas, and service studios', 'Restaurants taking reservations', 'Any local business that regularly misses calls'],
    results: [
      { stat: '100%', label: 'call answer rate' },
      { stat: '0', label: 'calls lost to voicemail' },
      { stat: '24/7', label: 'availability including holidays' },
      { stat: '65%', label: 'of calls fully resolved by agent' },
    ],
  },
  {
    slug: 'ai-operations-workflow-automation',
    title: 'AI Operations & Workflow Automation',
    tagline: 'The 10 hours a week your team spends on busywork — automated.',
    seoTitle: 'AI Operations Automation Las Vegas | Voice of Cash',
    seoDescription: 'Automate internal workflows, invoicing, reporting, task assignments, and the repetitive operations work that consumes your team every week.',
    icon: '⚙️',
    category: 'Operations',
    hourlyRate: 149,
    retainerFrom: 1500,
    setupFrom: 2800,
    heroStatement: 'Every hour your best people spend on repetitive tasks is an hour they are not growing your business.',
    problem: 'Operations waste is invisible until you measure it. How many hours per week does your team spend on tasks that follow a predictable pattern — invoice generation, status update emails, task assignment, reporting, data transfer between systems? In most businesses, the answer is 15 to 30 percent of total working hours.',
    solution: 'We map your internal operations, identify every workflow that follows a repeatable pattern, and automate it with an AI agent layer that executes those workflows without human intervention. The result is a team that spends their time on judgment-intensive work rather than pattern-matching tasks a machine can do better and faster.',
    whatWeDeliver: [
      'Operations audit identifying top automation opportunities by time saved',
      'Custom workflow automations for your highest-impact repetitive processes',
      'Invoice and billing automation triggered by project completion',
      'Internal reporting automations delivered on schedule without manual pulls',
      'Task creation and assignment automation based on project and pipeline triggers',
      'Inter-system data sync eliminating manual copy-paste between tools',
      'Process documentation for every automation built',
    ],
    process: [
      { step: '01', title: 'Operations Audit', body: 'We map every repetitive workflow in your business, calculate time cost, and prioritize by impact and automation feasibility.' },
      { step: '02', title: 'Automation Design', body: 'We design the automation architecture for your top 5 to 10 workflows and map every integration needed.' },
      { step: '03', title: 'Build & Test', body: 'We build each automation, test with real data, and validate outputs before replacing any manual process.' },
      { step: '04', title: 'Deploy & Document', body: 'Automations go live. Every workflow is documented so your team understands what is running and why.' },
    ],
    whoItsFor: ['Operations-heavy service businesses', 'Teams losing hours to manual reporting and data entry', 'Businesses scaling faster than their processes', 'Companies with multiple systems that do not talk to each other', 'Any organization where "that is just how we do it" is the answer too often'],
    results: [
      { stat: '15-30%', label: 'of team hours typically recovered' },
      { stat: '90%', label: 'reduction in manual reporting time' },
      { stat: '0', label: 'invoices that slip through the cracks' },
      { stat: '2-4wk', label: 'typical payback period' },
    ],
  },
  {
    slug: 'ai-competitor-intelligence',
    title: 'AI Competitor Intelligence Agent',
    tagline: 'Know what your competitors are doing before your clients do.',
    seoTitle: 'AI Competitor Intelligence Agent | Voice of Cash',
    seoDescription: 'Automated monitoring of competitor websites, pricing, reviews, and social presence. Weekly intelligence briefings so you always stay one step ahead.',
    icon: '🔍',
    category: 'Strategy',
    hourlyRate: 149,
    retainerFrom: 750,
    setupFrom: 1100,
    heroStatement: 'Your competitors are moving. Right now. Do you know where?',
    problem: 'Competitive intelligence is one of the most valuable inputs to business strategy — and almost universally underdone because it takes time nobody has. By the time you notice a competitor has changed their pricing, added a service, or run a campaign, they have already captured the customers you could have had.',
    solution: 'We deploy an AI competitor monitoring agent that watches your defined competitors continuously — their websites, pricing pages, review profiles, job postings, and social channels — and delivers a weekly intelligence briefing with only the changes and developments that matter. You stay current without spending a minute on research.',
    whatWeDeliver: [
      'Competitor monitoring across websites, pricing, reviews, and social profiles',
      'Change detection alerts for pricing updates, new service offerings, and messaging shifts',
      'Weekly competitive intelligence briefing in plain language',
      'Review sentiment tracking: how are their customers feeling vs. yours',
      'Job posting monitoring: what they are hiring for signals where they are growing',
      'Quarterly competitive landscape summary for strategic planning',
    ],
    process: [
      { step: '01', title: 'Competitive Mapping', body: 'We define your competitive set — direct competitors, adjacent threats, and aspirational benchmarks — and what to watch on each.' },
      { step: '02', title: 'Monitor Build', body: 'We configure the monitoring stack across all relevant channels and set alert thresholds for meaningful changes.' },
      { step: '03', title: 'Report Design', body: 'We design your weekly briefing format to surface only what is actionable — no noise, just signal.' },
      { step: '04', title: 'Ongoing Intel', body: 'Weekly briefings delivered automatically. Quarterly deep-dives on competitive positioning included in retainer.' },
    ],
    whoItsFor: ['Businesses in competitive local markets', 'Companies preparing for market expansion', 'Leadership teams doing quarterly strategic planning', 'Sales teams who need competitive positioning data', 'Any business that wants to stop being surprised by what competitors do'],
    results: [
      { stat: '5hrs', label: 'manual research replaced weekly' },
      { stat: '100%', label: 'competitor coverage automated' },
      { stat: '48hr', label: 'avg time to detect competitor changes' },
      { stat: 'Weekly', label: 'intelligence briefing delivered' },
    ],
  },
  {
    slug: 'ai-reporting-performance-dashboard',
    title: 'AI Reporting & Performance Dashboard',
    tagline: 'Every number your business produces, in one place, delivered to you automatically.',
    seoTitle: 'AI Reporting & Performance Dashboard | Voice of Cash',
    seoDescription: 'Pull data from every platform your business runs on, generate weekly performance summaries, and surface the insights that actually matter. Automated business intelligence.',
    icon: '📊',
    category: 'Strategy',
    hourlyRate: 149,
    retainerFrom: 1000,
    setupFrom: 1800,
    heroStatement: 'You cannot manage what you cannot see. And you cannot see what nobody is measuring.',
    problem: 'Most business owners are operating on intuition and lagging indicators. Revenue reports come at end of month. Marketing performance lives in six separate dashboards that nobody checks. The numbers that would tell you something is wrong are sitting in a platform you logged into two weeks ago.',
    solution: 'We build a unified AI reporting system that pulls data from every platform your business runs on — marketing, sales, operations, finance — and delivers automated performance summaries on your schedule. The system surfaces the metrics that matter and flags anomalies before they become problems. You get a weekly briefing that tells you exactly where your business stands without opening a single dashboard.',
    whatWeDeliver: [
      'Data integration from your active platforms: CRM, marketing, financial, operational',
      'Custom dashboard showing KPIs relevant to your specific business model',
      'Automated weekly performance summary email with plain-language insights',
      'Anomaly detection alerts for metrics that deviate from trend',
      'Monthly performance report for leadership or stakeholders',
      'Quarterly business review data package with trend analysis',
    ],
    process: [
      { step: '01', title: 'Metrics Audit', body: 'We define the KPIs that actually matter for your business and map every data source that needs to feed into your reporting.' },
      { step: '02', title: 'Integration Build', body: 'We connect all your data sources, build the unified data layer, and configure the automated summary generation.' },
      { step: '03', title: 'Dashboard Build', body: 'We build your dashboard and design the weekly summary format. You review and provide feedback before it goes live.' },
      { step: '04', title: 'Automate & Monitor', body: 'Reports run automatically. You get alerts when something needs attention and weekly summaries whether or not you think to check.' },
    ],
    whoItsFor: ['Business owners who want real visibility without dashboard fatigue', 'Leadership teams making data-driven decisions', 'Marketing teams reporting to ownership or clients', 'Operations teams tracking SLA and process performance', 'Any business where performance data is scattered and rarely synthesized'],
    results: [
      { stat: '0', label: 'manual report pulls after setup' },
      { stat: '100%', label: 'data sources connected and synced' },
      { stat: 'Weekly', label: 'performance briefings delivered' },
      { stat: '6', label: 'avg platforms unified into one view' },
    ],
  },
];

export function getServiceBySlug(slug: string) {
  return services.find(s => s.slug === slug);
}

// ── 26 additional services ──────────────────────────────
export const additionalServices: Service[] = [
  {
    slug: 'ai-internal-knowledge-base',
    title: 'AI Internal Knowledge Base',
    tagline: 'Every answer your team needs, found in seconds.',
    seoTitle: 'AI Internal Knowledge Base | Voice of Cash',
    seoDescription: 'AI-powered knowledge base that answers your team questions instantly from policies to processes. Stop answering the same questions twice.',
    icon: '🧠', category: 'Operations', hourlyRate: 149, retainerFrom: 800, setupFrom: 1600,
    heroStatement: 'Every time your best employee answers the same question twice, you are paying for the same work twice.',
    problem: 'Business knowledge lives in emails, docs nobody can find, and peoples heads. New hires ramp slowly. Senior staff get interrupted constantly.',
    solution: 'We build an AI knowledge base trained on your actual documentation and processes. Your team asks questions in plain language and gets accurate answers immediately.',
    whatWeDeliver: ['Knowledge audit and doc ingestion','AI Q&A interface for your full team','Policy, process, and product knowledge searchable in plain language','Continuous update system','Usage analytics showing most-asked questions'],
    process: [{ step:'01', title:'Audit', body:'We inventory every document and identify knowledge that lives only in peoples heads.' },{ step:'02', title:'Training', body:'We ingest source materials and train the AI on your terminology and context.' },{ step:'03', title:'Interface', body:'We build the team-facing interface and test accuracy.' },{ step:'04', title:'Deploy', body:'Live with quarterly update sessions.' }],
    whoItsFor: ['Businesses with high employee turnover','Teams scaling faster than docs can keep up','Any org where "just ask someone" is still the knowledge system'],
    results: [{ stat:'60%', label:'reduction in repetitive questions' },{ stat:'3x', label:'faster new hire ramp' },{ stat:'0', label:'knowledge lost when employees leave' }],
  },
  {
    slug: 'ai-contract-proposal-automation',
    title: 'AI Contract and Proposal Automation',
    tagline: 'Send a polished proposal 10 minutes after the discovery call.',
    seoTitle: 'AI Contract and Proposal Automation | Voice of Cash',
    seoDescription: 'Automate proposal generation, contract creation, and e-signature collection. Close deals before momentum fades.',
    icon: '📝', category: 'Revenue', hourlyRate: 149, retainerFrom: 900, setupFrom: 1500,
    heroStatement: 'The proposal that arrives tomorrow loses to the one that arrives tonight.',
    problem: 'Every hour between a great discovery call and a delivered proposal is an hour the prospect cools down and competing options enter their consideration.',
    solution: 'We build an AI proposal system that generates a customized, professional proposal from your discovery call notes in minutes. Scope, pricing, timeline, and terms all populated automatically.',
    whatWeDeliver: ['Proposal template system with dynamic field population','AI-generated copy from discovery inputs','E-signature collection with audit trail','Automated follow-up for unsigned proposals','Closed-loop reporting from send to signed'],
    process: [{ step:'01', title:'Templates', body:'We design your proposal templates and map decision logic for different scopes.' },{ step:'02', title:'AI Layer', body:'We build the generation workflow from discovery inputs to ready-to-send proposal.' },{ step:'03', title:'Signatures', body:'E-signature integration and follow-up automation.' },{ step:'04', title:'Training', body:'Sales team trained in one session.' }],
    whoItsFor: ['Service businesses with custom scope engagements','Agencies and consultants','Any business where proposals take more than an hour to produce'],
    results: [{ stat:'10min', label:'avg proposal turnaround post-call' },{ stat:'22%', label:'higher close rate vs. next-day proposals' },{ stat:'3hrs', label:'saved weekly per sales rep' }],
  },
  {
    slug: 'ai-hiring-recruitment-automation',
    title: 'AI Hiring and Recruitment Automation',
    tagline: 'Find the right hire faster. Spend zero time on the wrong ones.',
    seoTitle: 'AI Hiring and Recruitment Automation | Voice of Cash',
    seoDescription: 'Automate job posting, candidate screening, interview scheduling, and communication. Hire faster without adding HR headcount.',
    icon: '🤝', category: 'Operations', hourlyRate: 149, retainerFrom: 850, setupFrom: 1400,
    heroStatement: 'Every week a critical role sits open, your team covers the gap. That is not free.',
    problem: 'Most hiring time is spent screening candidates who are not a fit. Posting, reviewing, scheduling, sending status updates all take time operations leaders do not have.',
    solution: 'We build an AI hiring system that handles everything before the first serious interview: posting to multiple boards, screening resumes, running pre-screening, scheduling, and status communication.',
    whatWeDeliver: ['Multi-platform job posting automation','AI resume screening against your criteria','Asynchronous pre-screening interview','Interview scheduling automation','Candidate status communication throughout','Offer letter and e-signature automation'],
    process: [{ step:'01', title:'Role Profiling', body:'We document criteria and build screening logic.' },{ step:'02', title:'Build', body:'Posting, screening, and scheduling infrastructure built.' },{ step:'03', title:'Communications', body:'All candidate messaging written in your voice.' },{ step:'04', title:'Launch', body:'First role goes live.' }],
    whoItsFor: ['Businesses scaling headcount','Operations leaders spending hours on recruiting','Any company where a slow hire is a business problem'],
    results: [{ stat:'60%', label:'reduction in time-to-hire' },{ stat:'80%', label:'candidates screened without human review' },{ stat:'0', label:'candidates left without a status update' }],
  },
  {
    slug: 'ai-content-seo-engine',
    title: 'AI Content and SEO Engine',
    tagline: 'Rank for the searches your clients are already doing.',
    seoTitle: 'AI Content SEO Engine Las Vegas | Voice of Cash',
    seoDescription: 'AI-powered content strategy, production, and SEO. Blog posts, service pages, and local SEO content produced and published monthly.',
    icon: '🔎', category: 'Brand', hourlyRate: 149, retainerFrom: 1800, setupFrom: 2200,
    heroStatement: 'Your website has one job: bring in clients already looking for what you do.',
    problem: 'Most local business websites are digital brochures. They look good but do not rank without paid ads.',
    solution: 'We build an AI content and SEO engine that identifies high-value keywords, produces optimized content, and publishes consistently. Organic traffic compounds. Paid traffic stops when you stop paying.',
    whatWeDeliver: ['Keyword research and content gap analysis','Monthly content calendar with 6-12 posts','AI-drafted, human-reviewed blog content','On-page SEO optimization','Internal linking architecture','Monthly rank tracking report'],
    process: [{ step:'01', title:'Keywords', body:'We identify every keyword your clients search that you do not rank for.' },{ step:'02', title:'Strategy', body:'6-month content calendar built.' },{ step:'03', title:'Production', body:'Monthly content produced, optimized, and published.' },{ step:'04', title:'Track', body:'Monthly rank reports and quarterly strategy updates.' }],
    whoItsFor: ['Businesses relying too heavily on paid ads','Local businesses wanting to rank','Any company ready to invest in an asset that compounds'],
    results: [{ stat:'6mo', label:'typical timeframe to rank gains' },{ stat:'3x', label:'more organic traffic in 12 months' },{ stat:'30%', label:'lower cost per acquisition vs. paid' }],
  },
  {
    slug: 'ai-client-onboarding-automation',
    title: 'AI Client Onboarding Automation',
    tagline: 'The first impression after the sale. Make it flawless.',
    seoTitle: 'AI Client Onboarding Automation | Voice of Cash',
    seoDescription: 'Automate client onboarding: welcome sequences, document collection, kickoff scheduling, and portal access. Start every relationship strong.',
    icon: '🚀', category: 'Operations', hourlyRate: 149, retainerFrom: 850, setupFrom: 1400,
    heroStatement: 'The first 30 days of a client relationship determine whether they stay for 3 years or 3 months.',
    problem: 'Onboarding is the most critical phase and the most commonly ad-hoc. Documents collected twice. Welcome emails late. The first impression is disorganized.',
    solution: 'We build an automated onboarding system that delivers a professional experience from the moment a contract is signed. Every step triggered automatically.',
    whatWeDeliver: ['Automated welcome sequence on contract signature','Document collection with reminders','Kickoff scheduling linked to real availability','Client portal provisioning','Onboarding checklist visible to client and team','30-day satisfaction check-in'],
    process: [{ step:'01', title:'Map', body:'We document every step from contract signed to first deliverable.' },{ step:'02', title:'Build', body:'Full sequence built and integrated.' },{ step:'03', title:'Test', body:'Test onboarding from the client perspective.' },{ step:'04', title:'Deploy', body:'Every new client triggers the sequence automatically.' }],
    whoItsFor: ['Service businesses and agencies','Professional services firms','Any company where onboarding depends on one person remembering'],
    results: [{ stat:'100%', label:'of new clients onboarded consistently' },{ stat:'80%', label:'reduction in onboarding errors' },{ stat:'0', label:'documents collected via email thread' }],
  },
  {
    slug: 'ai-referral-program-automation',
    title: 'AI Referral Program Automation',
    tagline: 'Your best clients are your best sales team. Make it automatic.',
    seoTitle: 'AI Referral Program Automation | Voice of Cash',
    seoDescription: 'Build and automate a referral program that identifies happy clients, requests referrals at peak satisfaction, and rewards them automatically.',
    icon: '🔗', category: 'Revenue', hourlyRate: 149, retainerFrom: 700, setupFrom: 1100,
    heroStatement: 'Word of mouth is your highest-ROI channel. Most businesses leave it entirely to chance.',
    problem: 'Most businesses get referrals when a happy client happens to mention them. Nobody asks, tracks, thanks, or creates a reason to refer again.',
    solution: 'We build an AI referral system that identifies your happiest clients, asks at peak satisfaction, tracks every referral through the pipeline, and rewards automatically on conversion.',
    whatWeDeliver: ['Referral request automation on high-satisfaction signals','Referral tracking from intro to closed deal','Reward delivery automation','Referral partner portal','Monthly performance report','Reactivation sequences for lapsed referrers'],
    process: [{ step:'01', title:'Design', body:'Referral offer, tracking, and reward structure defined.' },{ step:'02', title:'Triggers', body:'Automation built to identify right clients at right moment.' },{ step:'03', title:'Tracking', body:'Pipeline tracking and reward delivery automated.' },{ step:'04', title:'Launch', body:'Program live with monthly reporting.' }],
    whoItsFor: ['Service businesses with repeat clients','High-NPS companies not capitalizing on satisfaction','Any company that gets referrals but has no system'],
    results: [{ stat:'3x', label:'more referrals vs. unstructured approach' },{ stat:'60%', label:'higher close rate on referred leads' },{ stat:'40%', label:'lower CAC vs. paid channels' }],
  },
  {
    slug: 'ai-churn-prediction-retention',
    title: 'AI Churn Prediction and Retention Agent',
    tagline: 'Know which clients are leaving before they tell you.',
    seoTitle: 'AI Churn Prediction Retention | Voice of Cash',
    seoDescription: 'AI that identifies at-risk clients from behavioral signals and triggers retention interventions before they cancel or go silent.',
    icon: '🛡️', category: 'Revenue', hourlyRate: 149, retainerFrom: 950, setupFrom: 1600,
    heroStatement: 'Retaining a client costs 5 to 7 times less than acquiring a new one.',
    problem: 'Client churn is usually predictable in hindsight. Engagement drops. Communication slows. You find out when the cancellation email arrives.',
    solution: 'We deploy an AI churn prediction agent that monitors behavioral signals and triggers retention interventions when a client shows early warning signs.',
    whatWeDeliver: ['Behavioral signal monitoring across CRM and communications','Churn risk scoring updated continuously','Automated retention outreach on risk thresholds','Internal alerts for high-value at-risk clients','Win-back sequence for churned clients','Monthly churn analytics'],
    process: [{ step:'01', title:'Signals', body:'We identify behavioral patterns that precede churn in your client base.' },{ step:'02', title:'Monitor', body:'Monitoring layer built across data sources.' },{ step:'03', title:'Flows', body:'Retention sequences written and automated.' },{ step:'04', title:'Track', body:'Monthly reports on churn rate and intervention effectiveness.' }],
    whoItsFor: ['Subscription and retainer businesses','SaaS companies with usage signals','Any company where losing a client represents significant loss'],
    results: [{ stat:'30%', label:'avg churn rate reduction' },{ stat:'72hrs', label:'avg time to identify at-risk client' },{ stat:'40%', label:'of at-risk clients saved by intervention' }],
  },
  {
    slug: 'ai-event-webinar-automation',
    title: 'AI Event and Webinar Automation',
    tagline: 'Run a world-class event without the back-office chaos.',
    seoTitle: 'AI Event and Webinar Automation | Voice of Cash',
    seoDescription: 'Automate registration, reminders, follow-ups, recordings, and post-event lead nurture for webinars, workshops, and live events.',
    icon: '🎤', category: 'Marketing', hourlyRate: 149, retainerFrom: 800, setupFrom: 1300,
    heroStatement: 'The event is 2 hours. The logistics are 20 hours. Not anymore.',
    problem: 'Events are high-converting but operationally expensive. Registration, reminders, recording distribution, follow-ups all manual.',
    solution: 'We build an end-to-end event automation system that handles everything from registration to post-event lead conversion.',
    whatWeDeliver: ['Registration with automatic confirmation and calendar invite','Multi-touch reminder sequence','Attendance-differentiated follow-up sequences','Recording delivery for no-shows','Post-event nurture timed to peak engagement','Re-engagement for no-shows'],
    process: [{ step:'01', title:'Map', body:'Every touchpoint from registration to conversion mapped.' },{ step:'02', title:'Build', body:'Full automation stack integrated with your webinar platform.' },{ step:'03', title:'Test', body:'Test registration through every touchpoint.' },{ step:'04', title:'Reuse', body:'System reusable for every subsequent event.' }],
    whoItsFor: ['Coaches running recurring webinars','B2B companies using events for lead gen','Any business that runs events but dreads the logistics'],
    results: [{ stat:'40%', label:'higher attendance with automated reminders' },{ stat:'100%', label:'of registrants receive follow-up' },{ stat:'15hrs', label:'saved per event in logistics' }],
  },
  {
    slug: 'ai-inventory-ordering-automation',
    title: 'AI Inventory and Ordering Automation',
    tagline: 'Never run out of what you need. Never over-order what you do not.',
    seoTitle: 'AI Inventory Ordering Automation | Voice of Cash',
    seoDescription: 'Automate inventory monitoring, reorder triggers, and vendor communication. Stop managing spreadsheets.',
    icon: '📦', category: 'Operations', hourlyRate: 149, retainerFrom: 1000, setupFrom: 1800,
    heroStatement: 'Stockouts cost revenue. Overstock costs cash. AI eliminates both.',
    problem: 'Inventory in most small businesses runs on spreadsheets and memory. Stockouts at the worst time. Overstock on slow movers. Manual ordering every week.',
    solution: 'We build an AI inventory system that monitors stock, triggers purchase orders at reorder points, and communicates with vendors automatically.',
    whatWeDeliver: ['Real-time inventory monitoring','Automated reorder triggers on par levels','Vendor order generation and communication','Low-stock and stockout alerts','Demand forecasting from historical patterns','Weekly inventory health report'],
    process: [{ step:'01', title:'Audit', body:'SKUs cataloged, par levels defined, vendors mapped.' },{ step:'02', title:'Build', body:'Monitoring and automation integrated with your POS or inventory system.' },{ step:'03', title:'Vendor', body:'Vendor communications configured and tested.' },{ step:'04', title:'Deploy', body:'System runs continuously with weekly reports.' }],
    whoItsFor: ['Retail businesses','Restaurants and food service','Any business where inventory management consumes significant manual effort'],
    results: [{ stat:'95%', label:'reduction in stockout events' },{ stat:'20%', label:'reduction in overstock carrying cost' },{ stat:'5hrs', label:'saved weekly on manual ordering' }],
  },
  {
    slug: 'ai-financial-close-automation',
    title: 'AI Financial Close and Bookkeeping Automation',
    tagline: 'Month-end close in days, not weeks.',
    seoTitle: 'AI Financial Close Automation | Voice of Cash',
    seoDescription: 'Automate transaction categorization, expense routing, invoice matching, and reporting. Compress your close cycle and get financials you can act on.',
    icon: '💰', category: 'Finance', hourlyRate: 149, retainerFrom: 1100, setupFrom: 2000,
    heroStatement: 'If your financials from last month arrive next month, you are managing with your eyes closed.',
    problem: 'Month-end close takes too long and the output arrives too late. Most of the work is pattern-matching that should not require human time.',
    solution: 'We build an AI financial automation layer that handles transaction categorization, expense routing, and invoice matching continuously so month-end becomes a verification step.',
    whatWeDeliver: ['Automated transaction categorization','Expense routing and approval workflow','Invoice matching against POs and receipts','Anomaly detection and variance flagging','Compressed close with automated reconciliation','Weekly financial summary to leadership'],
    process: [{ step:'01', title:'Audit', body:'Current close process mapped, highest-volume manual tasks identified.' },{ step:'02', title:'Build', body:'Automation layer integrated with your accounting system.' },{ step:'03', title:'Refine', body:'Parallel run for one close cycle, accuracy refined.' },{ step:'04', title:'Deploy', body:'Your team handles exceptions. The system handles the rest.' }],
    whoItsFor: ['Businesses with high transaction volume','Companies whose close takes more than 5 days','Any business that wants real-time financials'],
    results: [{ stat:'60%', label:'reduction in close cycle time' },{ stat:'90%', label:'transactions categorized automatically' },{ stat:'Weekly', label:'financials without manual builds' }],
  },
  {
    slug: 'ai-multi-location-management',
    title: 'AI Multi-Location Management Agent',
    tagline: 'Run every location like your best one.',
    seoTitle: 'AI Multi-Location Management | Voice of Cash',
    seoDescription: 'Standardize operations, reporting, and performance visibility across every location without adding management headcount.',
    icon: '🏢', category: 'Operations', hourlyRate: 149, retainerFrom: 2000, setupFrom: 3500,
    heroStatement: 'Your best location runs well because the right systems are in place. AI puts those systems everywhere.',
    problem: 'Multi-location businesses struggle with inconsistency. The best manager is not infinitely scalable. Performance data arrives late in inconsistent formats.',
    solution: 'We build a centralized AI operations layer that gives you standardized visibility, workflow automation, and anomaly detection across every location.',
    whatWeDeliver: ['Unified performance dashboard across all locations','Standardized automated reporting by location','Operational checklist automation','Anomaly detection for underperforming locations','Customer experience monitoring across locations'],
    process: [{ step:'01', title:'Audit', body:'Processes and performance standards documented.' },{ step:'02', title:'Build', body:'Central management layer connected to all locations.' },{ step:'03', title:'Rollout', body:'Location by location deployment with team training.' },{ step:'04', title:'Dashboard', body:'Leadership unified view. Managers get automated task prompts.' }],
    whoItsFor: ['Restaurant groups','Retail chains','Healthcare with multiple sites','Any business managing more than 2 locations'],
    results: [{ stat:'100%', label:'location visibility in one dashboard' },{ stat:'3hrs', label:'saved per location per week' },{ stat:'90%', label:'operational consistency across locations' }],
  },
  {
    slug: 'ai-training-course-delivery',
    title: 'AI Training and Course Delivery System',
    tagline: 'Sell your expertise once. Deliver it forever.',
    seoTitle: 'AI Training Course Delivery System | Voice of Cash',
    seoDescription: 'Automated course delivery that onboards students, delivers content on schedule, collects feedback, and converts completions into upsells.',
    icon: '🎓', category: 'Revenue', hourlyRate: 149, retainerFrom: 1000, setupFrom: 2000,
    heroStatement: 'You already know things people will pay to learn. The delivery system should not require your time every time.',
    problem: 'Building a course is hard, delivering it consistently is harder, and managing students manually makes the economics questionable.',
    solution: 'We build an AI course delivery system that onboards students automatically, drips content, prompts inactive students, collects feedback, and triggers upsells at completion.',
    whatWeDeliver: ['Automated student onboarding and platform access','Drip or completion-based content delivery','Progress tracking with inactivity prompts','Feedback collection at milestones','Completion certificate delivery','Upsell automation at completion'],
    process: [{ step:'01', title:'Map', body:'Curriculum mapped, delivery schedule defined, conversion moments identified.' },{ step:'02', title:'Build', body:'Delivery infrastructure connected to your course platform.' },{ step:'03', title:'Test', body:'One test cohort through the full system.' },{ step:'04', title:'Scale', body:'Every new student automated. You add cohorts.' }],
    whoItsFor: ['Coaches and consultants productizing expertise','Corporate trainers building scalable programs','Anyone whose knowledge is locked in 1-to-1 delivery'],
    results: [{ stat:'80%', label:'of course management automated' },{ stat:'3x', label:'more students per instructor hour' },{ stat:'40%', label:'higher completion rate' }],
  },
  {
    slug: 'ai-personalization-engine',
    title: 'AI Personalization Engine',
    tagline: 'Every client feels like your only client.',
    seoTitle: 'AI Personalization Engine | Voice of Cash',
    seoDescription: 'Build an AI personalization layer across your communications and offers that makes every interaction feel tailored to the individual at any scale.',
    icon: '🎯', category: 'Revenue', hourlyRate: 149, retainerFrom: 1400, setupFrom: 2400,
    heroStatement: 'The businesses that win on loyalty make clients feel known.',
    problem: 'At scale, personalization breaks down. Generic communication to a 3-year client sends a clear signal: you are a transaction, not a relationship.',
    solution: 'We build an AI personalization layer that pulls from every data point you have about a client and uses it to make every outreach and offer feel individually crafted.',
    whatWeDeliver: ['Client profile enrichment and data consolidation','Personalized email and SMS with dynamic content','Offer logic based on purchase and engagement history','Milestone recognition automation','Communication timing optimization','Monthly performance report with engagement lift'],
    process: [{ step:'01', title:'Audit', body:'Client data assessed across all touchpoints.' },{ step:'02', title:'Architecture', body:'Segmentation logic and dynamic content framework built.' },{ step:'03', title:'Content', body:'Variable content blocks written for each communication type.' },{ step:'04', title:'Deploy', body:'Live with A/B testing and monthly reporting.' }],
    whoItsFor: ['Businesses with repeat customers','E-commerce optimizing lifetime value','Any brand where loyalty is a competitive advantage'],
    results: [{ stat:'28%', label:'avg revenue lift from personalized offers' },{ stat:'3x', label:'higher engagement vs. generic' },{ stat:'60%', label:'better retention in personalized segments' }],
  },
  {
    slug: 'ai-pr-media-monitoring',
    title: 'AI PR and Media Monitoring',
    tagline: 'Know what is being said about your brand before it matters.',
    seoTitle: 'AI PR and Media Monitoring | Voice of Cash',
    seoDescription: 'Monitor brand mentions, press coverage, and industry conversations across news and social. Get alerts before a story escalates.',
    icon: '📡', category: 'Brand', hourlyRate: 149, retainerFrom: 700, setupFrom: 1000,
    heroStatement: 'The story about your brand is being written right now. Not by you.',
    problem: 'Most businesses find out about mentions and coverage after the fact. After the story gained traction. After the opportunity to respond has passed.',
    solution: 'We deploy an AI media monitoring agent that watches for your brand, executives, and keywords across news, social, forums, and reviews with real-time alerts.',
    whatWeDeliver: ['Brand mention monitoring across news, social, and reviews','Sentiment classification on every mention','Real-time alerts for significant coverage or negative spikes','Positive mention amplification opportunities','Weekly media summary with share of voice'],
    process: [{ step:'01', title:'Setup', body:'Monitoring keywords defined: brand, executives, products, competitors.' },{ step:'02', title:'Alerts', body:'Alert thresholds and formats configured.' },{ step:'03', title:'Integration', body:'Alerts delivered to Discord, Slack, or email.' },{ step:'04', title:'Ongoing', body:'Monthly share-of-voice reports. Quarterly keyword expansion.' }],
    whoItsFor: ['Brands with public presence','Executives with personal brand exposure','PR teams needing monitoring at scale'],
    results: [{ stat:'100%', label:'brand mentions captured' },{ stat:'15min', label:'avg alert time for significant coverage' },{ stat:'8hrs', label:'weekly manual monitoring replaced' }],
  },
  {
    slug: 'ai-lead-nurture-reactivation',
    title: 'AI Lead Nurture and Database Reactivation',
    tagline: 'The revenue is already in your database. Go get it.',
    seoTitle: 'AI Lead Nurture Database Reactivation | Voice of Cash',
    seoDescription: 'Reactivate cold leads and dormant clients with AI-personalized outreach. Most businesses have 3 to 5 times more revenue in their database than their active pipeline.',
    icon: '♻️', category: 'Revenue', hourlyRate: 149, retainerFrom: 900, setupFrom: 1400,
    heroStatement: 'You already paid to acquire those leads. Stop letting them collect dust.',
    problem: 'Most businesses have a database full of cold leads and quiet clients who expressed interest at some point. They are not lost. They are waiting for the right message.',
    solution: 'We build an AI reactivation campaign that segments your dormant database, crafts personalized sequences by segment, and routes re-engaged contacts back to your active pipeline.',
    whatWeDeliver: ['Database segmentation by recency, source, and intent','Personalized reactivation sequences per segment','Multi-channel outreach: email, SMS, voicemail','Re-engagement scoring','Hot lead routing to sales pipeline','Campaign performance report'],
    process: [{ step:'01', title:'Audit', body:'Dormant contacts segmented by age, source, and engagement history.' },{ step:'02', title:'Sequences', body:'Personalized reactivation sequences written per segment.' },{ step:'03', title:'Launch', body:'Campaigns launch by segment. Re-engaged contacts routed immediately.' },{ step:'04', title:'Repeat', body:'Most businesses run 2 to 3 cycles per year.' }],
    whoItsFor: ['Businesses with CRM databases older than 6 months','Companies that paid for leads and never closed them','Any business sitting on dormant revenue'],
    results: [{ stat:'8-15%', label:'reactivation rate on cold databases' },{ stat:'3-5x', label:'revenue potential vs. new lead cost' },{ stat:'0', label:'additional ad spend required' }],
  },
  // ── 11 SEO-targeted services ──────────────────────────
  {
    slug: 'ai-chatbot-website',
    title: 'AI Website Chatbot',
    tagline: 'Convert your website traffic instead of watching it leave.',
    seoTitle: 'AI Website Chatbot Las Vegas | Voice of Cash',
    seoDescription: 'Custom AI chatbot for your website that answers questions, qualifies leads, and books appointments 24/7. Not a generic bot — trained on your actual business.',
    icon: '💬', category: 'Revenue', hourlyRate: 149, retainerFrom: 750, setupFrom: 1200,
    heroStatement: 'Your website gets traffic. Most of it leaves without giving you a name.',
    problem: 'The average website converts less than 3 percent of visitors into leads. The other 97 percent leave without identifying themselves. A generic chatbot that says "How can I help?" does not change that. A chatbot trained on your business does.',
    solution: 'We build a custom AI chatbot trained on your services, FAQs, pricing, and conversion goals. It engages visitors in real conversation, qualifies them, and routes them to booking or follow-up based on their intent.',
    whatWeDeliver: ['Custom chatbot trained on your business','Lead qualification flow with CRM routing','Appointment booking integration','Handoff to human agent for high-intent visitors','Mobile-optimized chat interface','Monthly conversation analytics'],
    process: [{ step:'01', title:'Training', body:'Chatbot trained on your services, FAQs, and conversion goals.' },{ step:'02', title:'Build', body:'Deployed on your website with CRM and calendar integration.' },{ step:'03', title:'Test', body:'Conversation testing across all common visitor scenarios.' },{ step:'04', title:'Optimize', body:'Monthly tuning based on conversation data.' }],
    whoItsFor: ['Businesses with website traffic that is not converting','Service companies that want leads before visitors leave','Any business answering the same questions on every sales call'],
    results: [{ stat:'3x', label:'more leads from existing traffic' },{ stat:'90s', label:'avg response to visitor questions' },{ stat:'24/7', label:'coverage without staffing' }],
  },
  {
    slug: 'ai-voice-agent-conversational',
    title: 'AI Voice Agent — Conversational AI',
    tagline: 'Phone calls handled. Every time. On brand.',
    seoTitle: 'AI Voice Agent Conversational AI | Voice of Cash',
    seoDescription: 'Deploy a conversational AI voice agent that handles inbound calls, answers questions, books appointments, and routes escalations. Natural conversation, not an IVR.',
    icon: '🗣️', category: 'Operations', hourlyRate: 149, retainerFrom: 1200, setupFrom: 2200,
    heroStatement: 'The call that goes to voicemail calls your competitor next.',
    problem: 'IVR systems frustrate callers. Voicemail loses leads. Staffing for phone coverage is expensive and inconsistent. Conversational AI handles calls the way a professional human would — except it never calls in sick.',
    solution: 'We build and deploy a conversational AI voice agent trained on your business that handles inbound calls naturally, books appointments in real time, answers your actual FAQs, and escalates intelligently when a human is needed.',
    whatWeDeliver: ['Natural language voice agent trained on your business','Real-time calendar booking during the call','Custom call flows for different inquiry types','Full transcript delivered after every call','Urgent escalation to mobile number','After-hours message capture with next-day trigger'],
    process: [{ step:'01', title:'Script', body:'Full call scripts written including greetings, FAQ responses, booking flows, and escalations.' },{ step:'02', title:'Build', body:'Voice agent built and integrated with your phone system and calendar.' },{ step:'03', title:'Test', body:'Test calls across every scenario before go-live.' },{ step:'04', title:'Deploy', body:'Live on your business line with weekly call analytics.' }],
    whoItsFor: ['Medical, dental, and legal offices','Home services contractors','Any local business that regularly misses calls'],
    results: [{ stat:'100%', label:'call answer rate' },{ stat:'0', label:'calls lost to voicemail' },{ stat:'65%', label:'of calls fully resolved by agent' }],
  },
  {
    slug: 'ai-google-ads-optimization',
    title: 'AI Google Ads Optimization',
    tagline: 'Stop paying for clicks that do not convert.',
    seoTitle: 'AI Google Ads Optimization Las Vegas | Voice of Cash',
    seoDescription: 'AI-powered Google Ads management that continuously optimizes bids, keywords, and copy to lower your cost per lead and increase conversion rate.',
    icon: '📈', category: 'Marketing', hourlyRate: 149, retainerFrom: 1000, setupFrom: 1600,
    heroStatement: 'If your Google Ads account has not been touched in 30 days, it is hemorrhaging money.',
    problem: 'Google Ads requires continuous management to perform. Bids decay. Quality scores drift. Negative keyword lists go stale. Most businesses set it and forget it — and wonder why CPL keeps climbing.',
    solution: 'We deploy an AI optimization layer over your Google Ads account that continuously monitors performance, adjusts bids based on real conversion data, refines keywords, and tests ad variations to lower cost per lead and increase ROAS.',
    whatWeDeliver: ['Account audit identifying waste and opportunity','Continuous bid optimization based on conversion data','Keyword expansion and negative keyword management','Ad copy testing with statistical significance thresholds','Landing page performance analysis and recommendations','Weekly performance report: spend, CPL, ROAS, conversion rate'],
    process: [{ step:'01', title:'Audit', body:'Full account audit identifying waste, structure issues, and optimization opportunities.' },{ step:'02', title:'Rebuild', body:'Campaign restructure, bid strategy overhaul, and keyword refinement.' },{ step:'03', title:'Automate', body:'AI optimization layer deployed with continuous monitoring.' },{ step:'04', title:'Report', body:'Weekly performance reports with recommended actions.' }],
    whoItsFor: ['Businesses spending $3K+ per month on Google Ads','Companies with climbing CPL and declining conversion rates','Any advertiser not actively managing their account'],
    results: [{ stat:'30%', label:'avg CPL reduction in first 90 days' },{ stat:'2x', label:'improvement in quality score' },{ stat:'40%', label:'reduction in wasted ad spend' }],
  },
  {
    slug: 'ai-document-processing-ocr',
    title: 'AI Document Processing and OCR Automation',
    tagline: 'Stop paying people to read and type.',
    seoTitle: 'AI Document Processing OCR Automation | Voice of Cash',
    seoDescription: 'Automate data extraction from invoices, contracts, forms, and documents. AI reads, classifies, extracts, and routes data without human data entry.',
    icon: '📄', category: 'Operations', hourlyRate: 149, retainerFrom: 900, setupFrom: 1500,
    heroStatement: 'If someone on your team spends any part of their day re-typing information from one document into another system, that is a solved problem.',
    problem: 'Manual document processing is slow, expensive, and error-prone. Invoices keyed into accounting systems. Forms transcribed into CRMs. Contracts read by hand for key terms. All of it pattern-matching work that AI handles faster and more accurately.',
    solution: 'We build an AI document processing pipeline that reads your inbound documents — invoices, contracts, applications, forms — extracts the relevant data fields, validates them, and routes them to the right system automatically.',
    whatWeDeliver: ['Document classification by type','Data extraction from invoices, contracts, and forms','Validation rules to flag exceptions for human review','Automated data entry into your target systems','Processing audit trail for compliance','Monthly volume and accuracy reporting'],
    process: [{ step:'01', title:'Document Audit', body:'We catalog every document type flowing through your business and identify the data fields needed from each.' },{ step:'02', title:'Pipeline Build', body:'Extraction and routing pipeline built for your document types.' },{ step:'03', title:'Validation', body:'Exception rules configured for human review triggers.' },{ step:'04', title:'Deploy', body:'Pipeline processes documents automatically. Exceptions flagged for review.' }],
    whoItsFor: ['Finance teams processing high invoice volumes','Legal and real estate operations with contract review','HR departments processing applications','Any business with significant manual data entry from documents'],
    results: [{ stat:'90%', label:'reduction in manual data entry' },{ stat:'99%+', label:'extraction accuracy on structured documents' },{ stat:'5x', label:'faster processing vs. manual' }],
  },
  {
    slug: 'ai-real-estate-lead-automation',
    title: 'AI Real Estate Lead Automation',
    tagline: 'Match buyers to listings before your competitors pick up the phone.',
    seoTitle: 'AI Real Estate Lead Automation Las Vegas | Voice of Cash',
    seoDescription: 'AI that responds to real estate inquiries in under 90 seconds, qualifies buyers and sellers, matches new listings to buyer profiles, and schedules showings automatically.',
    icon: '🏡', category: 'Revenue', hourlyRate: 149, retainerFrom: 1200, setupFrom: 1800,
    heroStatement: 'Real estate leads have a half-life of about 5 minutes. Your AI responds in 90 seconds.',
    problem: 'Real estate is one of the most lead-sensitive industries in existence. Response time is the single biggest driver of conversion. Most agents and teams are still responding hours later — or the next morning.',
    solution: 'We build an AI lead automation system for real estate that responds to every inquiry instantly, qualifies buyers and sellers with smart questions, matches new listings to existing buyer profiles the moment they hit the market, and books showings directly into your calendar.',
    whatWeDeliver: ['90-second response to every lead across all sources','Buyer and seller qualification flows','New listing to buyer profile matching and automated outreach','Showing scheduling direct to calendar','Drip nurture for leads not ready to act now','Monthly pipeline report by lead source'],
    process: [{ step:'01', title:'Lead Audit', body:'All lead sources mapped and response workflow designed.' },{ step:'02', title:'Build', body:'AI qualification flows and matching logic built.' },{ step:'03', title:'Integrate', body:'CRM, calendar, and MLS integrations connected.' },{ step:'04', title:'Deploy', body:'Agent goes live. Every lead gets a response.' }],
    whoItsFor: ['Real estate agents missing leads to slow response','Teams with multiple agents and inconsistent follow-up','Brokerages looking to convert more of their existing lead volume'],
    results: [{ stat:'90s', label:'response time to every lead' },{ stat:'3x', label:'more showings booked per lead volume' },{ stat:'80%', label:'reduction in time-to-first-contact' }],
  },
  {
    slug: 'ai-ecommerce-catalog-automation',
    title: 'AI E-Commerce Catalog and Product Automation',
    tagline: 'Scale your product catalog without scaling your writing team.',
    seoTitle: 'AI E-Commerce Catalog Automation | Voice of Cash',
    seoDescription: 'AI that writes SEO-optimized product descriptions, generates metadata, manages catalog updates, and automates inventory alerts for e-commerce businesses.',
    icon: '🛒', category: 'Operations', hourlyRate: 149, retainerFrom: 1100, setupFrom: 1800,
    heroStatement: 'Every product without a good description is a product that does not sell itself.',
    problem: 'E-commerce businesses with large catalogs face an impossible tradeoff: writing quality product descriptions takes significant time, but every product without one loses search visibility and conversion rate.',
    solution: 'We build an AI product content pipeline that generates SEO-optimized descriptions, titles, and metadata for your entire catalog — and keeps it updated as products change, seasonal relevance shifts, and new inventory arrives.',
    whatWeDeliver: ['AI-generated SEO product descriptions at catalog scale','Title and metadata optimization for search visibility','Bulk catalog update automation','Low-stock and out-of-stock alert routing','Product category page content','Monthly catalog performance report'],
    process: [{ step:'01', title:'Catalog Audit', body:'Current description quality assessed, SEO gaps identified.' },{ step:'02', title:'Template Build', body:'AI generation templates built per product category.' },{ step:'03', title:'Generation', body:'Full catalog generated and reviewed for quality.' },{ step:'04', title:'Maintain', body:'New product descriptions generated automatically on SKU addition.' }],
    whoItsFor: ['E-commerce businesses with 50+ SKUs','Retailers launching new product lines','Any store where product descriptions are a bottleneck'],
    results: [{ stat:'100%', label:'catalog coverage with optimized descriptions' },{ stat:'3x', label:'faster new product launch content' },{ stat:'25%', label:'avg conversion rate lift with quality descriptions' }],
  },
  {
    slug: 'ai-healthcare-patient-communication',
    title: 'AI Healthcare Patient Communication Automation',
    tagline: 'Every patient feels like a priority. Without burning out your staff.',
    seoTitle: 'AI Healthcare Patient Communication Las Vegas | Voice of Cash',
    seoDescription: 'HIPAA-aware AI automation for appointment reminders, follow-up sequences, intake forms, and patient satisfaction surveys for medical and dental practices.',
    icon: '🏥', category: 'Operations', hourlyRate: 149, retainerFrom: 1200, setupFrom: 2000,
    heroStatement: 'Your front desk is managing appointments, answering phones, and handling check-in simultaneously. AI takes two of those three off their plate.',
    problem: 'Healthcare practices lose revenue to no-shows, miss opportunities to reactivate patients due for visits, and frustrate patients with slow communication. Front desk staff are stretched thin and patient experience suffers.',
    solution: 'We build a HIPAA-aware patient communication automation system that handles appointment reminders, recall sequences for patients due for follow-up, intake form delivery, and post-visit satisfaction collection without involving front desk staff.',
    whatWeDeliver: ['Appointment reminder sequences via SMS and email','Patient recall automation for overdue visits','Digital intake form delivery and collection','Post-visit satisfaction survey automation','No-show reactivation sequences','Front desk call deflection for common inquiries'],
    process: [{ step:'01', title:'Compliance Review', body:'HIPAA compliance requirements mapped to automation design.' },{ step:'02', title:'Workflow Build', body:'Reminder, recall, intake, and satisfaction workflows built.' },{ step:'03', title:'Integration', body:'Connected to your practice management system.' },{ step:'04', title:'Deploy', body:'Live with weekly performance metrics.' }],
    whoItsFor: ['Medical and dental practices','Chiropractic, physical therapy, and wellness providers','Any healthcare business with high appointment volume'],
    results: [{ stat:'35%', label:'reduction in no-show rate' },{ stat:'4hrs', label:'saved weekly by front desk per provider' },{ stat:'2x', label:'more recall patients reactivated' }],
  },
  {
    slug: 'ai-legal-document-automation',
    title: 'AI Legal Document Automation',
    tagline: 'Routine legal documents done in minutes, not hours.',
    seoTitle: 'AI Legal Document Automation | Voice of Cash',
    seoDescription: 'Automate generation of routine legal documents, client intake, case status communication, and document review. Free attorney time for billable work.',
    icon: '⚖️', category: 'Operations', hourlyRate: 149, retainerFrom: 1300, setupFrom: 2200,
    heroStatement: 'Attorneys are most valuable doing legal work. Not drafting the same NDA for the 40th time.',
    problem: 'Legal operations are document-heavy. Routine agreements, client communications, intake forms, and status updates consume paralegal and attorney time that could be billable.',
    solution: 'We build an AI legal document automation system that generates routine documents from templates, handles client intake and status communication, and flags documents needing attorney attention — without creating compliance risk.',
    whatWeDeliver: ['Routine document generation from templates','Client intake automation with e-signature collection','Case status communication automation','Document review workflow with attorney review triggers','Conflict check integration','Matter closing checklist automation'],
    process: [{ step:'01', title:'Document Audit', body:'Routine documents cataloged and templates built.' },{ step:'02', title:'Automation Build', body:'Generation and routing workflows built with attorney review triggers.' },{ step:'03', title:'Compliance Review', body:'All automations reviewed for jurisdiction compliance.' },{ step:'04', title:'Deploy', body:'Live with attorney override available on every document.' }],
    whoItsFor: ['Solo and small firm attorneys','Legal departments with high routine document volume','Any legal practice where admin tasks compete with billable hours'],
    results: [{ stat:'70%', label:'reduction in routine document time' },{ stat:'3hrs', label:'additional billable time recovered per attorney weekly' },{ stat:'0', label:'status update calls from automated communication' }],
  },
];

export const allServices: Service[] = [...services, ...additionalServices];
